# Generated by Django 4.2.9 on 2026-02-17 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_from", models.DateField(db_index=True)),
                ("contract_to", models.DateField(db_index=True)),
                (
                    "rent_amount_at_contract",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "advance_paid_months",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "service_charge_at_contract",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="accounts.household",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "db_table": "rental_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalContractParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Tenant"),
                            ("dependent", "Dependent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="contracts.rentalcontract",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_participations",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "db_table": "rental_contract_participants",
                "indexes": [
                    models.Index(
                        fields=["contract", "role"],
                        name="rental_cont_contrac_5a58cf_idx",
                    )
                ],
                "unique_together": {("contract", "household")},
            },
        ),
        migrations.CreateModel(
            name="RentalContractAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Author"),
                            ("co-author", "Co-Author"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_approve", models.BooleanField(default=False)),
                ("can_terminate", models.BooleanField(default=False)),
                ("can_renew", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="contracts.rentalcontract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_authorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rental_contract_authors",
                "indexes": [
                    models.Index(
                        fields=["contract", "is_active"],
                        name="rental_cont_contrac_0591a6_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="rental_cont_user_id_b985f0_idx",
                    ),
                ],
                "unique_together": {("contract", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["unit", "status"], name="rental_cont_unit_id_4ddc67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["tenant_household", "status"],
                name="rental_cont_tenant__adad28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(
                fields=["contract_from", "contract_to"],
                name="rental_cont_contrac_574139_idx",
            ),
        ),
    ]
