# Generated by Django 4.2.9 on 2026-02-17 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billing_month",
                    models.CharField(
                        db_index=True, help_text="Format: YYYY-MM", max_length=7
                    ),
                ),
                ("due_date", models.DateField(db_index=True)),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("partial", "Partially Paid"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., utility bill number)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="contracts.rentalcontract",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for rent bills",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="properties.utilitytype",
                    ),
                ),
            ],
            options={
                "db_table": "bills",
                "ordering": ["-billing_month", "-due_date"],
                "indexes": [
                    models.Index(
                        fields=["contract", "billing_month"],
                        name="bills_contrac_0a9b7f_idx",
                    ),
                    models.Index(
                        fields=["contract", "status"], name="bills_contrac_5c5e7b_idx"
                    ),
                    models.Index(
                        fields=["due_date", "status"], name="bills_due_dat_46fdc6_idx"
                    ),
                ],
                "unique_together": {("contract", "billing_month", "utility_type")},
            },
        ),
    ]
