# Generated by Django 4.2.9 on 2026-02-17 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(blank=True, max_length=255, null=True)),
                ("village", models.CharField(blank=True, max_length=255, null=True)),
                ("ward", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "zone_or_union",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city_corporation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "upazila_or_thana",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("district", models.CharField(max_length=255)),
                ("division", models.CharField(max_length=255)),
                ("country", models.CharField(default="Bangladesh", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_name", models.CharField(max_length=255)),
                (
                    "age_of_building",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("has_lift", models.BooleanField(default=False)),
                ("has_security_guard", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("is_tiled", models.BooleanField(default=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="properties.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apartment_no", models.CharField(max_length=50)),
                (
                    "floor_no",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "facing_direction",
                    models.CharField(
                        choices=[
                            ("north", "North"),
                            ("south", "South"),
                            ("east", "East"),
                            ("west", "West"),
                            ("north_east", "North-East"),
                            ("north_west", "North-West"),
                            ("south_east", "South-East"),
                            ("south_west", "South-West"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size_sqft",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "units",
                "ordering": ["property", "floor_no", "apartment_no"],
            },
        ),
        migrations.CreateModel(
            name="UtilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "utility_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalTerms",
            fields=[
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="rental_terms",
                        serialize=False,
                        to="properties.unit",
                    ),
                ),
                (
                    "asking_rent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_rent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "advance_months",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_due_day",
                    models.IntegerField(
                        default=5,
                        help_text="Day of month when rent is due (1-31)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Rental Terms",
                "db_table": "rental_terms",
            },
        ),
        migrations.CreateModel(
            name="UnitPolicy",
            fields=[
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="policy",
                        serialize=False,
                        to="properties.unit",
                    ),
                ),
                ("pets_allowed", models.BooleanField(default=False)),
                ("bachelor_allowed", models.BooleanField(default=True)),
                ("sublet_allowed", models.BooleanField(default=False)),
                (
                    "gender_restricted",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male Only"),
                            ("female", "Female Only"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("roof_access", models.BooleanField(default=False)),
                ("roof_gardening_allowed", models.BooleanField(default=False)),
                ("house_gardening_allowed", models.BooleanField(default=False)),
                ("ac_installation_allowed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Unit Policies",
                "db_table": "unit_policy",
            },
        ),
        migrations.CreateModel(
            name="UnitRoomSummary",
            fields=[
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="room_summary",
                        serialize=False,
                        to="properties.unit",
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "master_bedrooms",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "attached_baths",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "common_baths",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "kitchens",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "balconies",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("has_separate_dining", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Unit Room Summaries",
                "db_table": "unit_room_summary",
            },
        ),
        migrations.CreateModel(
            name="UnitUtility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("meter", "Meter-based"),
                            ("card", "Card/Prepaid"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_included_in_rent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="properties.unit",
                    ),
                ),
                (
                    "utility_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_utilities",
                        to="properties.utilitytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unit Utilities",
                "db_table": "unit_utility",
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["district", "division"], name="locations_distric_8f82b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["upazila_or_thana"], name="locations_upazila_cb3b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitutility",
            index=models.Index(
                fields=["unit", "utility_type"], name="unit_utilit_unit_id_3f69fc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unitutility",
            unique_together={("unit", "utility_type")},
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["property", "floor_no"], name="units_propert_95e5cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("property", "apartment_no")},
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["location", "created_at"], name="properties_locatio_39c204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["created_by"], name="properties_created_a41892_idx"
            ),
        ),
    ]
