# Generated by Django 4.2.9 on 2026-02-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity (e.g., RentalContract, Payment)",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(db_index=True, help_text="ID of the entity"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("terminate", "Terminate"),
                            ("renew", "Renew"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Snapshot of changed data"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs_entity__d4c2e5_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "created_at"],
                        name="audit_logs_actor_u_b024de_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_logs_content_b0ef47_idx",
                    ),
                ],
            },
        ),
    ]
